// <auto-generated />
using System;
using Fit.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fit.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230817171945_cpf-Tabela-Aluno")]
    partial class cpfTabelaAluno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Fit.API.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Altura")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Cpf")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("Date");

                    b.Property<string>("FotoAluno")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAluno")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoSanguineo")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.HasKey("IdAluno");

                    b.ToTable("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
